name: Build & deploy test

on:
  push:
    branches:
      - env/test
  pull_request:
    branches:
      - env/test

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
    
    - name: Install NPM packages
      run: npm ci
    
    - name: Build project
      run: npm run build
    
    - name: Upload test-ready build files
      uses: actions/upload-artifact@v2
      with:
        name: build-files
        path: ./build
  
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/env/test'
    
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: build-files
        path: ./build

    - name: Deploy to Test Location
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
    - name: Deploy with rsync
      run: rsync -avz ./build/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.DEPLOY_LOC_TEST }}
